workflows:
  ios-release:
    name: "eSign : Sign Any Docs iOS Release"
    instance_type: mac_mini_m2
    integrations:
      app_store_connect: kamiaccount
    environment:
      flutter: stable
      xcode: latest
      cocoapods: default
      ios_signing:
        distribution_type: app_store
        bundle_identifier: com.esign.signanydocs
    scripts:
      - name: Install dependencies
        script: flutter pub get
      - name: Build signed IPA
        script: flutter build ipa --release
    artifacts:
      - build/ios/ipa/*.ipa
      - /tmp/xcodebuild_logs/*.log
    publishing:
      app_store_connect:
        auth: integration
